[project]
name = "amazing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "termcolor>=3.3.0",
    "textual>=8.0.2",
    "mazegen",
    "textual-canvas>=1.1.0",
    "mypy>=1.19.1",
]

[tool.uv.workspace]
members = [
    "maze_generator",
]

[tool.uv.sources]
mazegen = { workspace = true }

[tool.mypy]
mypy_path = "maze_generator"
explicit_package_bases = true
